package com.myspace.gestioncredito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datoCredito implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "descripción solicitud")
	private java.lang.String descripciónSolicitud;
	@org.kie.api.definition.type.Label(value = "gasto persona")
	private int gastoPersona;
	@org.kie.api.definition.type.Label(value = "tiempo amortizacion ")
	private int tiempoAmortiza;
	@org.kie.api.definition.type.Label(value = "valor credito")
	private int valorCredito;
	@org.kie.api.definition.type.Label(value = "total deudas")
	private int totalDeudas;

	public datoCredito() {
	}

	public java.lang.String getDescripciónSolicitud() {
		return this.descripciónSolicitud;
	}

	public void setDescripciónSolicitud(java.lang.String descripciónSolicitud) {
		this.descripciónSolicitud = descripciónSolicitud;
	}

	public int getGastoPersona() {
		return this.gastoPersona;
	}

	public void setGastoPersona(int gastoPersona) {
		this.gastoPersona = gastoPersona;
	}

	public int getTiempoAmortiza() {
		return this.tiempoAmortiza;
	}

	public void setTiempoAmortiza(int tiempoAmortiza) {
		this.tiempoAmortiza = tiempoAmortiza;
	}

	public int getValorCredito() {
		return this.valorCredito;
	}

	public void setValorCredito(int valorCredito) {
		this.valorCredito = valorCredito;
	}

	public int getTotalDeudas() {
		return this.totalDeudas;
	}

	public void setTotalDeudas(int totalDeudas) {
		this.totalDeudas = totalDeudas;
	}

	public datoCredito(java.lang.String descripciónSolicitud, int gastoPersona,
			int tiempoAmortiza, int valorCredito, int totalDeudas) {
		this.descripciónSolicitud = descripciónSolicitud;
		this.gastoPersona = gastoPersona;
		this.tiempoAmortiza = tiempoAmortiza;
		this.valorCredito = valorCredito;
		this.totalDeudas = totalDeudas;
	}

}