package com.myspace.gestioncredito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class tiempoDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("data time")
	private java.lang.String dataTime;
	@org.kie.api.definition.type.Label("time zone")
	private java.lang.String timeZone;
	@org.kie.api.definition.type.Label("unix time")
	private java.lang.String unixTime;

	public tiempoDTO() {
	}

	public java.lang.String getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(java.lang.String dataTime) {
		this.dataTime = dataTime;
	}

	public java.lang.String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(java.lang.String timeZone) {
		this.timeZone = timeZone;
	}

	public java.lang.String getUnixTime() {
		return this.unixTime;
	}

	public void setUnixTime(java.lang.String unixTime) {
		this.unixTime = unixTime;
	}

	public tiempoDTO(java.lang.String dataTime, java.lang.String timeZone,
			java.lang.String unixTime) {
		this.dataTime = dataTime;
		this.timeZone = timeZone;
		this.unixTime = unixTime;
	}

}